#!/bin/sh
DIR_NAME=$(basename "$PWD")
HASH=$(echo "$PWD" | sha256sum | cut -c1-4)
NAME="${DIR_NAME}-${HASH}"

tmux attach -t "$NAME" || tmux \
  new-session -s "$NAME" "nvim ." \; \
  rename-window "nvim" \; \
  split-window -v \; \
  resize-pane -y 25% \; \
  select-pane -t 0 \; \
  new-window -n "claude" "$HOME/.local/bin/claude --dangerously-skip-permissions" \; \
  new-window -n "lazygit" lazygit \; \
  select-window -t 1 \; \
  attach
